server {
    listen 80;
    server_name staging.winter-prosper.com;

    root /home/web/projects/staging/myweb/current/dist;
    index index.html;

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }

    location /_astro/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 1000;
}
